from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
from typing import Any

from .paths import ensure_path_layout

SERVICE_NAMES = {
    "hot_watch": "sherpamind-hot-watch.service",
    "alert_dispatch": "sherpamind-alert-dispatch.service",
    "maintenance": "sherpamind-maintenance.service",
}

SERVICE_RESOURCE_LIMITS = {
    "hot_watch": {
        "CPUQuota": "25%",
        "CPUWeight": "30",
        "IOWeight": "30",
        "Nice": "10",
        "TasksMax": "128",
    },
    "alert_dispatch": {
        "CPUQuota": "10%",
        "CPUWeight": "20",
        "IOWeight": "20",
        "Nice": "10",
        "TasksMax": "128",
    },
    "maintenance": {
        "CPUQuota": "50%",
        "CPUWeight": "20",
        "IOWeight": "20",
        "Nice": "10",
        "TasksMax": "128",
    },
}

SERVICE_ENV_FILE_NAME = "service.env"


def _read_openclaw_skill_entry() -> dict[str, str]:
    config_path = Path.home() / ".openclaw" / "openclaw.json"
    if not config_path.exists():
        return {}
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return {}
    entry = (((data.get("skills") or {}).get("entries") or {}).get("sherpamind") or {})
    return entry if isinstance(entry, dict) else {}


@dataclass
class ServiceCommandResult:
    status: str
    message: str
    details: dict[str, Any] | None = None


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _unit_path(name: str) -> Path:
    return Path.home() / ".config" / "systemd" / "user" / name


def _run(args: list[str], check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, text=True, capture_output=True, check=check)


def _quote_env_value(value: str) -> str:
    return shlex.quote(value.strip())


def _service_env_file_path() -> Path:
    return ensure_path_layout().secrets_root / SERVICE_ENV_FILE_NAME


def _read_key_value_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip().strip("'\"")
    return values


def _read_secret_file(path: Path) -> str | None:
    try:
        value = path.read_text(encoding="utf-8").strip()
    except OSError:
        return None
    return value or None


def _openclaw_hook_env_values() -> dict[str, str]:
    config_path = Path.home() / ".openclaw" / "openclaw.json"
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return {}
    hooks = data.get("hooks") if isinstance(data.get("hooks"), dict) else {}
    token = hooks.get("token") if isinstance(hooks.get("token"), str) else None
    if hooks.get("enabled") is not True or not token or not token.strip():
        return {}
    gateway = data.get("gateway") if isinstance(data.get("gateway"), dict) else {}
    port = gateway.get("port") if isinstance(gateway.get("port"), int) else 18789
    path = hooks.get("path") if isinstance(hooks.get("path"), str) and hooks.get("path", "").strip() else "/hooks"
    path = "/" + path.strip().strip("/")
    return {
        "SHERPAMIND_OPENCLAW_WEBHOOK_URL": f"http://127.0.0.1:{port}{path}/agent",
        "SHERPAMIND_OPENCLAW_WEBHOOK_TOKEN": token.strip(),
    }


def _write_service_env_file() -> Path | None:
    paths = ensure_path_layout()
    skill_entry = _read_openclaw_skill_entry()
    staged_settings = _read_key_value_file(paths.settings_file)
    values: dict[str, str] = {}
    api_key = skill_entry.get("apiKey")
    if isinstance(api_key, str) and api_key.strip():
        values["SHERPADESK_API_KEY"] = api_key.strip()
    api_user = skill_entry.get("apiUser")
    if isinstance(api_user, str) and api_user.strip():
        values["SHERPADESK_API_USER"] = api_user.strip()
    values.update({key: value for key, value in _openclaw_hook_env_values().items() if value})
    staged_url = staged_settings.get("SHERPAMIND_OPENCLAW_WEBHOOK_URL")
    if staged_url:
        values["SHERPAMIND_OPENCLAW_WEBHOOK_URL"] = staged_url
    staged_token = _read_secret_file(paths.openclaw_webhook_token_file)
    if staged_token:
        values["SHERPAMIND_OPENCLAW_WEBHOOK_TOKEN"] = staged_token
    env_file = paths.secrets_root / SERVICE_ENV_FILE_NAME
    if not values:
        return env_file if env_file.exists() else None
    env_file.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# SherpaMind service-only secret environment.",
        "# Generated by `python3 scripts/run.py install-service` from local OpenClaw skill config.",
    ]
    for key in sorted(values):
        lines.append(f"{key}={_quote_env_value(values[key])}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        env_file.chmod(0o600)
    except OSError:
        pass
    return env_file


def _base_env_lines() -> list[str]:
    paths = ensure_path_layout()
    env_lines = [f"Environment=SHERPAMIND_WORKSPACE_ROOT={paths.workspace_root}"]
    if os.getenv("SHERPAMIND_ROOT") or paths.root != paths.workspace_root / ".SherpaMind":
        env_lines.append(f"Environment=SHERPAMIND_ROOT={paths.root}")
    env_lines.append(f"EnvironmentFile=-{_service_env_file_path()}")
    return env_lines


def _resource_limit_lines(service_key: str) -> list[str]:
    limits = SERVICE_RESOURCE_LIMITS[service_key]
    return [f"{key}={value}" for key, value in limits.items()]


def unit_contents(service_key: str = "maintenance") -> str:
    paths = ensure_path_layout()
    repo = _repo_root()
    python = paths.runtime_venv / "bin" / "python"
    exec_map = {
        "hot_watch": "hot-watch-run",
        "alert_dispatch": "alert-dispatch-run",
        "maintenance": "maintenance-run",
    }
    desc_map = {
        "hot_watch": "SherpaMind hot watch worker",
        "alert_dispatch": "SherpaMind alert dispatch worker",
        "maintenance": "SherpaMind maintenance worker",
    }
    env_block = "\n".join(_base_env_lines())
    resource_block = "\n".join(_resource_limit_lines(service_key))
    return f"""[Unit]
Description={desc_map[service_key]}
After=default.target
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
WorkingDirectory={repo}
{env_block}
{resource_block}
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
ExecStart={python} -m sherpamind.cli {exec_map[service_key]}
Restart=on-failure
RestartSec=30
TimeoutStopSec=45

[Install]
WantedBy=default.target
"""


def write_unit_files() -> list[Path]:
    written: list[Path] = []
    env_file = _write_service_env_file()
    for service_key, service_name in SERVICE_NAMES.items():
        path = _unit_path(service_name)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(unit_contents(service_key))
        written.append(path)
    if env_file is not None:
        written.append(env_file)
    legacy = _unit_path("sherpamind.service")
    if legacy.exists():
        legacy.unlink()
    return written


def daemon_reload() -> None:
    _run(["systemctl", "--user", "daemon-reload"])


def service_status() -> dict[str, Any]:
    units: dict[str, Any] = {}
    all_enabled = True
    all_active = True
    for service_key, service_name in SERVICE_NAMES.items():
        unit = _unit_path(service_name)
        enabled = _run(["systemctl", "--user", "is-enabled", service_name], check=False)
        active = _run(["systemctl", "--user", "is-active", service_name], check=False)
        unit_status = {
            "unit_path": str(unit),
            "unit_exists": unit.exists(),
            "enabled": enabled.returncode == 0 and enabled.stdout.strip() == "enabled",
            "active": active.returncode == 0 and active.stdout.strip() == "active",
            "enabled_raw": enabled.stdout.strip() or enabled.stderr.strip(),
            "active_raw": active.stdout.strip() or active.stderr.strip(),
        }
        all_enabled = all_enabled and unit_status["enabled"]
        all_active = all_active and unit_status["active"]
        units[service_key] = unit_status
    return {
        "units": units,
        "enabled": all_enabled,
        "active": all_active,
    }


def install_service(start_now: bool = True) -> ServiceCommandResult:
    units = write_unit_files()
    daemon_reload()
    for service_name in SERVICE_NAMES.values():
        _run(["systemctl", "--user", "enable", service_name])
    if start_now:
        for service_name in SERVICE_NAMES.values():
            _run(["systemctl", "--user", "restart", service_name])
    return ServiceCommandResult(status="ok", message="SherpaMind services installed.", details={"unit_paths": [str(u) for u in units], **service_status()})


def uninstall_service(stop_now: bool = True) -> ServiceCommandResult:
    for service_name in SERVICE_NAMES.values():
        if stop_now:
            _run(["systemctl", "--user", "stop", service_name], check=False)
        _run(["systemctl", "--user", "disable", service_name], check=False)
        unit = _unit_path(service_name)
        if unit.exists():
            unit.unlink()
    daemon_reload()
    return ServiceCommandResult(status="ok", message="SherpaMind services uninstalled.", details=service_status())


def restart_service() -> ServiceCommandResult:
    for service_name in SERVICE_NAMES.values():
        _run(["systemctl", "--user", "restart", service_name])
    return ServiceCommandResult(status="ok", message="SherpaMind services restarted.", details=service_status())


def stop_service() -> ServiceCommandResult:
    for service_name in SERVICE_NAMES.values():
        _run(["systemctl", "--user", "stop", service_name], check=False)
    return ServiceCommandResult(status="ok", message="SherpaMind services stopped.", details=service_status())


def start_service() -> ServiceCommandResult:
    for service_name in SERVICE_NAMES.values():
        _run(["systemctl", "--user", "start", service_name])
    return ServiceCommandResult(status="ok", message="SherpaMind services started.", details=service_status())


def doctor_service() -> dict[str, Any]:
    status = service_status()
    paths = ensure_path_layout()
    systemctl_available = shutil.which("systemctl") is not None
    return {
        **status,
        "runtime_python_exists": (paths.runtime_venv / "bin" / "python").exists(),
        "settings_file_exists": paths.settings_file.exists(),
        "api_user_file_exists": paths.api_user_file.exists(),
        "service_log_exists": paths.service_log.exists(),
        "hot_watch_log_exists": paths.hot_watch_log.exists(),
        "alert_dispatch_log_exists": paths.alert_dispatch_log.exists(),
        "maintenance_log_exists": paths.maintenance_log.exists(),
        "service_state_exists": paths.service_state_file.exists(),
        "systemctl_user_available": systemctl_available,
    }
